"""Tests for sendsprint/scaffolder.py — discover, generate (offline+LLM), write."""

from __future__ import annotations

import json
import subprocess
from pathlib import Path

from sendsprint.scaffolder import (
    _DESIGN_SECTIONS,
    _DOMAIN_SECTIONS,
    _PATTERNS_SECTIONS,
    _VISION_SECTIONS,
    SPEC_FILES,
    Scaffolder,
    _add_header,
    _build_prompt,
    _offline_body,
)

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _seed_repo(repo: Path) -> None:
    """Init a git repo with a package.json + README so detect_tech finds 'react'."""
    repo.mkdir(parents=True, exist_ok=True)
    (repo / "package.json").write_text(
        json.dumps({"name": "smoke", "version": "1.0.0", "dependencies": {"react": "19"}}),
        encoding="utf-8",
    )
    (repo / "README.md").write_text("# Smoke\n\nDemo repo.\n", encoding="utf-8")
    subprocess.run(["git", "init", "-q"], cwd=repo, check=True)
    subprocess.run(["git", "add", "-A"], cwd=repo, check=True)
    subprocess.run(
        ["git", "-c", "user.email=a@b.c", "-c", "user.name=Test", "commit", "-q", "-m", "init"],
        cwd=repo,
        check=True,
    )


class _FakeLlm:
    """LLM stub — records prompts and returns a canned body keyed by section header."""

    def __init__(self) -> None:
        self.calls: list[tuple[str, str | None]] = []

    def complete(self, prompt: str, *, system: str | None = None, max_tokens: int = 2000) -> str:
        self.calls.append((prompt, system))
        for line in prompt.splitlines():
            if line.startswith("- ") and len(line) > 2:
                marker = line[2:].strip()
                return f"## {marker}\n\nGenerated body for {marker}.\n"
        return "## Stub\n\n_TODO:_\n"


# ---------------------------------------------------------------------------
# discover()
# ---------------------------------------------------------------------------


def test_discover_collects_signals(tmp_path: Path) -> None:
    _seed_repo(tmp_path)
    signals = Scaffolder(tmp_path).discover()

    assert signals.repo_path == tmp_path.resolve()
    assert signals.file_count >= 2
    assert "package.json" in signals.manifests
    assert "README.md" in signals.docs
    assert "react" in signals.primary_languages
    assert "init" in signals.git_log
    assert signals.fingerprint_json.startswith("{")


def test_discover_handles_missing_docs_and_manifests(tmp_path: Path) -> None:
    """Repo with only a tracked .gitkeep — no manifest, no docs."""
    tmp_path.mkdir(parents=True, exist_ok=True)
    (tmp_path / ".gitkeep").write_text("", encoding="utf-8")
    subprocess.run(["git", "init", "-q"], cwd=tmp_path, check=True)
    subprocess.run(["git", "add", "-A"], cwd=tmp_path, check=True)
    subprocess.run(
        ["git", "-c", "user.email=a@b.c", "-c", "user.name=Test", "commit", "-q", "-m", "init"],
        cwd=tmp_path,
        check=True,
    )

    signals = Scaffolder(tmp_path).discover()
    assert signals.manifests == {}
    assert signals.docs == {}
    assert signals.file_count >= 1


# ---------------------------------------------------------------------------
# generate(offline=True)
# ---------------------------------------------------------------------------


def test_generate_offline_builds_all_four_specs(tmp_path: Path) -> None:
    _seed_repo(tmp_path)
    scaf = Scaffolder(tmp_path)
    signals = scaf.discover()

    outputs = scaf.generate(signals, offline=True)

    assert set(outputs) == {"vision", "domain", "design", "patterns"}
    for key, body in outputs.items():
        assert body.startswith(f"# {key.capitalize()}\n")
        assert "auto-generated by `sendsprint init`" in body
        assert "### Detected" in body
        assert "_TODO:_" in body


def test_generate_offline_invokes_on_step_callback(tmp_path: Path) -> None:
    _seed_repo(tmp_path)
    scaf = Scaffolder(tmp_path)
    signals = scaf.discover()

    seen: list[str] = []
    scaf.generate(signals, offline=True, on_step=seen.append)

    assert seen == ["vision", "domain", "design", "patterns"]


# ---------------------------------------------------------------------------
# generate(LLM path)
# ---------------------------------------------------------------------------


def test_generate_llm_calls_client_per_spec(tmp_path: Path) -> None:
    _seed_repo(tmp_path)
    fake = _FakeLlm()
    scaf = Scaffolder(tmp_path, llm=fake)
    signals = scaf.discover()

    outputs = scaf.generate(signals, offline=False)

    assert len(fake.calls) == 4
    systems = {system for _, system in fake.calls}
    assert systems == {Scaffolder.PROMPT_HEADER}
    for key, body in outputs.items():
        assert body.startswith(f"# {key.capitalize()}\n")
        assert "Generated body for" in body


def test_generate_llm_invokes_on_step_callback(tmp_path: Path) -> None:
    _seed_repo(tmp_path)
    scaf = Scaffolder(tmp_path, llm=_FakeLlm())
    signals = scaf.discover()

    seen: list[str] = []
    scaf.generate(signals, offline=False, on_step=seen.append)

    assert seen == ["vision", "domain", "design", "patterns"]


# ---------------------------------------------------------------------------
# write()
# ---------------------------------------------------------------------------


def test_write_creates_spec_files_and_skips_existing(tmp_path: Path) -> None:
    _seed_repo(tmp_path)
    scaf = Scaffolder(tmp_path)
    outputs = scaf.generate(scaf.discover(), offline=True)

    first = scaf.write(outputs)
    assert {p.name for p in first.created} == {"VISION.md", "DOMAIN.md", "DESIGN.md", "PATTERNS.md"}
    assert first.skipped == []
    for p in first.created:
        assert p.is_file()

    second = scaf.write(outputs)
    assert second.created == []
    assert {p.name for p in second.skipped} == {
        "VISION.md",
        "DOMAIN.md",
        "DESIGN.md",
        "PATTERNS.md",
    }


def test_write_force_overwrites(tmp_path: Path) -> None:
    _seed_repo(tmp_path)
    scaf = Scaffolder(tmp_path)
    outputs = scaf.generate(scaf.discover(), offline=True)
    scaf.write(outputs)

    overwritten = scaf.write(outputs, force=True)
    assert {p.name for p in overwritten.created} == {
        "VISION.md",
        "DOMAIN.md",
        "DESIGN.md",
        "PATTERNS.md",
    }
    assert overwritten.skipped == []


def test_write_targets_match_spec_files_map(tmp_path: Path) -> None:
    _seed_repo(tmp_path)
    scaf = Scaffolder(tmp_path)
    outputs = scaf.generate(scaf.discover(), offline=True)
    result = scaf.write(outputs)

    rel = {p.relative_to(tmp_path) for p in result.created}
    assert rel == set(SPEC_FILES.values())


# ---------------------------------------------------------------------------
# run() end-to-end
# ---------------------------------------------------------------------------


def test_run_offline_end_to_end(tmp_path: Path) -> None:
    _seed_repo(tmp_path)
    seen: list[str] = []
    result = Scaffolder(tmp_path).run(offline=True, on_step=seen.append)

    assert result.signals is not None
    assert len(result.created) == 4
    assert seen == ["vision", "domain", "design", "patterns"]
    for path in result.created:
        text = path.read_text()
        assert "auto-generated by `sendsprint init`" in text
        assert "_TODO:_" in text


# ---------------------------------------------------------------------------
# Module-level helpers
# ---------------------------------------------------------------------------


class _FakeSignals:
    """Minimal RepoSignals shape for helper tests."""

    primary_languages = ["react", "typescript"]
    file_count = 42
    manifests = {"package.json": "{}"}
    docs = {"README.md": "# x"}
    fingerprint_json = "{}"
    git_log = "abc init"
    git_authors = "1\tTest"


def test_offline_body_lists_facts_and_sections() -> None:
    body = _offline_body(_VISION_SECTIONS, _FakeSignals())  # type: ignore[arg-type]
    assert "techs: react, typescript" in body
    assert "files: 42" in body
    assert "manifests: package.json" in body
    assert "docs: README.md" in body
    for section in _VISION_SECTIONS:
        assert section in body
        assert "_TODO:_" in body


def test_build_prompt_includes_facts_and_sections() -> None:
    prompt = _build_prompt(
        title="DESIGN.md",
        sections=_DESIGN_SECTIONS,
        signals=_FakeSignals(),  # type: ignore[arg-type]
    )
    assert "Generate `DESIGN.md`" in prompt
    assert "### Tech fingerprint" in prompt
    assert "package.json" in prompt
    assert "README.md" in prompt
    for section in _DESIGN_SECTIONS:
        assert section.lstrip("# ").strip() in prompt


def test_add_header_prepends_banner_and_strips_duplicate_h1() -> None:
    body = "# Vision\n\nbody text\n"
    result = _add_header("vision", "2026-05-07", body)

    assert result.startswith("# Vision\n")
    assert "auto-generated by `sendsprint init` on 2026-05-07" in result
    assert result.count("# Vision\n") == 1
    assert "body text" in result


def test_section_constants_have_expected_shape() -> None:
    for sections in (_VISION_SECTIONS, _DOMAIN_SECTIONS, _DESIGN_SECTIONS, _PATTERNS_SECTIONS):
        assert len(sections) >= 5
        assert all(s.startswith("## ") for s in sections)
