export const theme = {
  bg: "#f5f7fb",
  bgDeep: "#eef2f7",
  surface: "#ffffff",
  surfaceAlt: "#f8fafc",
  surfaceMuted: "#f1f5f9",
  border: "#e5e9f0",
  borderStrong: "#cdd5e0",
  text: "#0f172a",
  textMuted: "#64748b",
  textSoft: "#94a3b8",
  primary: "#1e63ec",
  primarySoft: "#3b82f6",
  primaryFaint: "#eef4ff",
  accent: "#38a9f7",
  accentWarm: "#f59e0b",
  success: "#16a34a",
  successSoft: "#dcfce7",
  warning: "#d97706",
  warningSoft: "#fef3c7",
  danger: "#dc2626",
  dangerSoft: "#fee2e2",
  info: "#2563eb",
  infoSoft: "#dbeafe",
  fontSans:
    'Inter, -apple-system, BlinkMacSystemFont, "Segoe UI", "Helvetica Neue", Arial, sans-serif',
  fontMono:
    'ui-monospace, SFMono-Regular, Menlo, Consolas, "Liberation Mono", monospace',
  radius: 10,
  radiusSmall: 6,
  radiusLarge: 14,
  spacing: (n: number) => n * 4,
} as const;

export type Theme = typeof theme;
